Circle ci setup
odk-x/sync-endpoint pull request #95
Opened 2023-11-05 10:48 UTC by r0ssing

Merging proposal of @tr-sangale 's ci/cd setup with the an added commit containing the removal of extra "env" command (https://github.com/odk-x/sync-endpoint/commit/d0518afb82bfd9f61ac33bd3a6453cf975d05304)

2023-11-05 14:17 UTC, wbrunette requested changes

2023-11-05 14:17 UTC, wbrunette commented on mysql-test/pom.xml
> +        <groupId>org.odk-x</groupId>
We have not changed the namespace yet, this will cause problems. Again once we have a build system we will do a complete change.

2023-11-05 14:17 UTC, wbrunette commented on mysql-test/pom.xml
> +        <version>1.0.0</version>
This number is actually important it cross links a bunch of stuff, leave as is.

2023-11-05 14:17 UTC, wbrunette commented on odk-rest-interface/settings.xml
> +          <id>central</id>
We aren't pushing to central (at least yet) we are maintaining final versions on GitHub I thought (in another URL was goal).

2024-09-01 13:13 UTC, tr-sangale approved these changes
Hello, was unavailable due to unavoidable reasons for a long, so approving it now.

2024-09-01 14:29 UTC, wbrunette commented
Work was moved to update-jdk11

2024-09-01 14:29 UTC, closed without merging